[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "weather_data_pipeline"
version = "0.1.0"
description = "Weather data platform ingestion logic"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]