services:
  postgres:
    image: postgres:14
    container_name: local-postgres
    restart: always

    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=20"
      - "-c"
      - "max_wal_senders=20"
      - "-c"
      - "wal_keep_size=512MB"

    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_password

    ports:
      - "5433:5432"

    volumes:
      - postgres_data_cdc:/var/lib/postgresql/data
      - ${PROJECT_ROOT}/infra/local/postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weather_user -d weather_prod"]
      interval: 10s
      retries: 5

volumes:
  postgres_data_cdc:
